### ISSUE TITLE
How about tracking error rate?

### ISSUE THREAD

**Issue by ax-nathan** [tylertreat/bench#2]
Currently, if a `Requester` returns an error, bench bails on the run. It could be useful (and interesting) to continue and capture some statistics around error rates, and error-case latency distribution as well. What do you think?

**Comment by tylertreat** [comment]
What statistics would you want captured with regards to errors? How would you incorporate error-case latency into the histogram? Would a second histogram for errors be useful?

**Comment by ax-nathan** [comment]
Thanks for `bench`, BTW. It has already become part of my workflow, and I expect it will get even better with time. When I get some spare cycles (in hard startup mode ATM), I'd like to contribute...

I think that adding "TotalErrors" to the summary and recording a distinct errors histogram would cover the basics and be immediately useful. Sometimes you need to know how long it takes to fail...especially if there are upstream systems involved!

**Comment by tylertreat** [comment]
Makes sense. I would agree this would be useful.

**Comment by ax-nathan** [comment]
Banged out a quick implementation that doesn't change the existing behavior. Working for me...

**Comment by tylertreat** [comment]
Addressed in #3.
